# Generated by Django 5.0.6 on 2024-06-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_blog_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="slug",
        ),
    ]
