# Generated by Django 5.0.6 on 2024-06-07 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_blog_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_date",
            field=models.DateTimeField(
                auto_created=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="опубликован"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(blank=True, null=True, upload_to="media/photo"),
        ),
    ]
