# Generated by Django 5.0.6 on 2024-06-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blog_slug_alter_blog_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="опубликован"),
        ),
    ]
