# Generated by Django 5.0.6 on 2024-06-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="view_counter",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Просмотры"
            ),
        ),
    ]
